apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: bsi-hello
    newName: ito2005/bsi-hello-k8s
    newTag: c58b625834eb8b45c0d3d3b45ba4cbc288fc5146