apiVersion: v1
kind: Service 
metadata:
  name: bsi-hello-service
spec:
  selector:
    app: bsi-hello
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: bsi-hello-service